AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model to deploy K9Finder Resources
Parameters:
  COGNITOCLIENTID:
    Type: String
  COGNITOCLIENTSECRET:
    Type: String
  COGNITOUSERPOOLID:
    Type: String
Resources:
  K9FinderHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              Audience:
                - !Ref COGNITOCLIENTID
              Issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${COGNITOUSERPOOLID}"
  k9FinderAPITestingSAM:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/ 
      Description: ''
      MemorySize: 128
      Timeout: 3
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          COGNITO_CLIENT_ID: !Ref COGNITOCLIENTID
          COGNITO_CLIENT_SECRET: !Ref COGNITOCLIENTSECRET
          COGNITO_USER_POOL_ID: !Ref COGNITOUSERPOOLID
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Sid: CognitoPermissions
              Effect: Allow
              Action:
                - cognito-idp:AdminDeleteUser
                - cognito-idp:AdminCreateUser
                - cognito-idp:AdminAddUserToGroup
                - cognito-idp:AdminUpdateUserAttributes
                - cognito-idp:AdminGetUser
                - cognito-idp:ListUsers
              Resource: arn:aws:cognito-idp:us-east-1:050451372171:userpool/us-east-1_IvczIRf2M
            - Sid: DynamoDBPermissions
              Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
              Resource: arn:aws:dynamodb:us-east-1:050451372171:table/k9finder
            - Sid: GeneralReadOnlyAccess
              Action:
                - application-autoscaling:DescribeScalableTargets
                - application-autoscaling:DescribeScalingActivities
                - application-autoscaling:DescribeScalingPolicies
                - cloudwatch:DescribeAlarmHistory
                - cloudwatch:DescribeAlarms
                - cloudwatch:DescribeAlarmsForMetric
                - cloudwatch:GetMetricStatistics
                - cloudwatch:ListMetrics
                - cloudwatch:GetMetricData
                - datapipeline:DescribeObjects
                - datapipeline:DescribePipelines
                - datapipeline:GetPipelineDefinition
                - datapipeline:ListPipelines
                - datapipeline:QueryObjects
                - dynamodb:BatchGetItem
                - dynamodb:Describe*
                - dynamodb:List*
                - dynamodb:GetAbacStatus
                - dynamodb:GetItem
                - dynamodb:GetResourcePolicy
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:PartiQLSelect
                - dax:Describe*
                - dax:List*
                - dax:GetItem
                - dax:BatchGetItem
                - dax:Query
                - dax:Scan
                - ec2:DescribeVpcs
                - ec2:DescribeSubnets
                - ec2:DescribeSecurityGroups
                - iam:GetRole
                - iam:ListRoles
                - kms:DescribeKey
                - kms:ListAliases
                - sns:ListSubscriptionsByTopic
                - sns:ListTopics
                - lambda:ListFunctions
                - lambda:ListEventSourceMappings
                - lambda:GetFunctionConfiguration
                - resource-groups:ListGroups
                - resource-groups:ListGroupResources
                - resource-groups:GetGroup
                - resource-groups:GetGroupQuery
                - tag:GetResources
                - kinesis:ListStreams
                - kinesis:DescribeStream
                - kinesis:DescribeStreamSummary
              Effect: Allow
              Resource: '*'
            - Sid: CCIAccess
              Action:
                - cloudwatch:GetInsightRuleReport
              Effect: Allow
              Resource: arn:aws:cloudwatch:*:*:insight-rule/DynamoDBContributorInsights*
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-east-1:050451372171:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - arn:aws:logs:us-east-1:050451372171:log-group:/aws/lambda/k9FinderAPI:*
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Events:
        UsersGetAll:
          Type: HttpApi
          Properties:
            ApiId: !Ref K9FinderHttpApi
            Path: /users
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
        UsersCreate:
          Type: HttpApi
          Properties:
            ApiId: !Ref K9FinderHttpApi
            Path: /users
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer
        UsersDelete:
          Type: HttpApi
          Properties:
            ApiId: !Ref K9FinderHttpApi
            Path: /users/{id}
            Method: delete
            Auth:
              Authorizer: CognitoAuthorizer
        UsersUpdate:
          Type: HttpApi
          Properties:
            ApiId: !Ref K9FinderHttpApi
            Path: /users/{id}
            Method: put
            Auth:
              Authorizer: CognitoAuthorizer
        UsersGetById:
          Type: HttpApi
          Properties:
            ApiId: !Ref K9FinderHttpApi
            Path: /users/{id}
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
        GetAllDogs:
          Type: HttpApi
          Properties:
            ApiId: !Ref K9FinderHttpApi
            Path: /dogs
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
        CreateDog:
          Type: HttpApi
          Properties:
            ApiId: !Ref K9FinderHttpApi
            Path: /dogs
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer
        GetDogById:
          Type: HttpApi
          Properties:
            ApiId: !Ref K9FinderHttpApi
            Path: /dogs/{id}
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer
        DeleteDog:
          Type: HttpApi
          Properties:
            ApiId: !Ref K9FinderHttpApi
            Path: /dogs/{id}
            Method: delete
            Auth:
              Authorizer: CognitoAuthorizer
        UpdateDog:
           Type: HttpApi
           Properties:
             ApiId: !Ref K9FinderHttpApi
             Path: /dogs/{id}
             Method: put
             Auth:
               Authorizer: CognitoAuthorizer
        Login:
           Type: HttpApi
           Properties:
             ApiId: !Ref K9FinderHttpApi
             Path: /login
             Method: post
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto