name: Build and Test

on:
  push:
    branches: [ "fix-download-artifact-gh-actions" ]
  # pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      dynamodb-local:
        image : amazon/dynamodb-local:latest
        ports:
          - 8000:8000
    env:
      IS_LOCAL: true
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
      COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      SECRET_HASH: ${{ secrets.SECRET_HASH }}
      TEST_USERNAME_2: ${{ secrets.TEST_USERNAME_2 }}
      TEST_USERNAME_ADMIN: ${{ secrets.TEST_USERNAME_ADMIN }}
      TEST_USERNAME_SHELTER: ${{ secrets.TEST_USERNAME_SHELTER }}
      COGNITO_CLIENT_SECRET: ${{ secrets.COGNITO_CLIENT_SECRET }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run unit
    - run: npm run integration
    
  package_and_upload_artifact:
    name: Package and Upload Artifact
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/fix-download-artifact-gh-actions' }}
    steps:
      - uses: actions/checkout@v4
      # if: ${{ github.event.workflow_run.head_branch == 'fix-download-artifact-gh-actions' }}
      - run: npm ci
      - run: npm run build
      - run: zip -r k9Finder.zip dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: k9Finder.zip
          path: k9Finder.zip