# https://www.timveletta.com/blog/pushing-content-to-s3-from-github-actions/

name: Deploy Artifact to Lambda
on:
  workflow_run:
    workflows: ["Download and Deploy Artifact"]
    types:
      - completed
  push:
    branches: [ "main" ]
  pull_request:
env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: k9Finder.zip
      - name: Sync files to S3 bucket
        run: |
          aws s3 cp k9Finder.zip s3://k9finderhost/k9Finder.zip
      - name: Update Lambda function
        run: |
          aws lambda update-function-code \
            --function-name k9FinderAPI \
            --s3-bucket k9finderhost \
            --s3-key k9Finder.zip \
            --region us-east-1