name: IAC with AWS SAM
on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed
env:
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
  COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
  COGNITO_CLIENT_SECRET: ${{ secrets.COGNITO_CLIENT_SECRET }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: build SAM application
        run: sam build

      - name: Deploy SAM application
        run: |
                  sam deploy --no-confirm-changeset --no-fail-on-empty-changeset \
                  --stack-name "${{ secrets.SAM_STACK_NAME }}" \
                  --s3-bucket "${{ secrets.SAM_S3_BUCKET }}" \
                  --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
                  --region "${{ secrets.AWS_REGION }}" \
                  --parameter-overrides \
                    COGNITO_CLIENT_ID=${{ secrets.COGNITO_CLIENT_ID }} \
                    COGNITO_CLIENT_SECRET=${{ secrets.COGNITO_CLIENT_SECRET }} \
                    COGNITO_USER_POOL_ID=${{ secrets.COGNITO_USER_POOL_ID }} \
                    SECRET_HASH=${{ secrets.SECRET_HASH }} \
                    TEST_PASSWORD=${{ secrets.TEST_PASSWORD }} \
                    TEST_USERNAME=${{ secrets.TEST_USERNAME }}