name: k6 Test

on:
  workflow_run:
    workflows: ["Download and Deploy Artifact to Lambda"]
    types:
      - completed

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
      - name: Run k6 tests
        uses: grafana/run-k6-action@v1
        env:
          TEST_USERNAME_ADMIN: ${{ secrets.TEST_USERNAME_ADMIN }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
        with:
          path: |
            ./tests/performance/**
            ./tests/app*.js