name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Break out lint and test into separate jobs
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      dynamodb-local:
        image : amazon/dynamodb-local:latest
        ports:
          - 8000:8000
    env:
      IS_LOCAL: true
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: 'dynamodbLocalDummyKeyId'
      AWS_SECRET_ACCESS_KEY: 'dynamodbLocalDummyAccessKey'
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run supertest
    - run: npm run build
    - run: zip -r k9Finder.zip dist/
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: k9Finder.zip
        path: k9Finder.zip

#make this conditional to only upload to s3 when merging to main

# https://www.timveletta.com/blog/pushing-content-to-s3-from-github-actions/
  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: k9Finder.zip
      - name: Sync files to S3 bucket
        run: |
          aws s3 cp k9Finder.zip s3://k9finderhost/k9Finder.zip

  # Look into signed URLs for S3
  # Write down points on what I will present/hand up at the end. What's the goal?
  #v2 - add lambda deploys