name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Break out lint and test into separate jobs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        name: Use Node.js 18.x
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run supertest
    - run: ls -l
    - run: zip -r test-s3.zip test-s3
    - run: ls -l

#make this conditional to only upload to s3 when merging to main

# https://www.timveletta.com/blog/pushing-content-to-s3-from-github-actions/
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Sync files to S3 bucket
        run: |
          aws s3 cp test-s3.zip s3://k9finderhost

    

  

  #Get S3 working as first version of build pipeline
  # Write up some details about it and how I would improve it
  # Look into signed URLs for S3
  # Write down points on what I will present/hand up at the end. What's the goal?
  #v2 - add lambda deploys