name: Test Code

on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      dynamodb-local:
        image : amazon/dynamodb-local:latest
        ports:
          - 8000:8000
    env:
      IS_LOCAL: true
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
      COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      TEST_USERNAME_ADMIN: ${{ secrets.TEST_USERNAME_ADMIN }}
      TEST_USERNAME_ADOPTER: ${{ secrets.TEST_USERNAME_ADOPTER }}
      TEST_USERNAME_SHELTER: ${{ secrets.TEST_USERNAME_SHELTER }}
      COGNITO_CLIENT_SECRET: ${{ secrets.COGNITO_CLIENT_SECRET }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run unit
    - run: npm run integration